const XINGHUO_HTTP_API_KEY = '';
const XINHUO_WS_APPID = '';
const XINGHUO_WS_APISECRET = '';
const XINGHUO_WS_APIKEY = '';
export {
    XINGHUO_HTTP_API_KEY,
    XINHUO_WS_APPID,
    XINGHUO_WS_APISECRET,
    XINGHUO_WS_APIKEY
};
