const XINGHUO_HTTP_API_KEY = 'zLfpNZvrZSLvwrDCsueE:nabJCDnWXHakLlfPpZQV';
const XINHUO_WS_APPID = '890bbf04';
const XINGHUO_WS_APISECRET = 'Y2U1MGNhOTMwY2Q0ODVkNjc0MmU1YTA4';
const XINGHUO_WS_APIKEY = 'd1dc120c997af3c7b752a84211670d90';
export {
    XINGHUO_HTTP_API_KEY,
    XINHUO_WS_APPID,
    XINGHUO_WS_APISECRET,
    XINGHUO_WS_APIKEY
};