import { createApp } from 'vue';
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
import LoginApp from './login_views/index.vue';
import 'element-plus/dist/index.css';
import '@/common/css/index/index.scss';
import '@/common/css/font/font.css';
import '@/common/css/fixed/index.scss';
import '@/common/css/fixed/map.scss';
import '@/common/css/fixed/light.scss';
import '@/Tailwind.css';
const app = createApp(LoginApp);
const pinia: any = createPinia();
pinia.use(piniaPluginPersistedstate);
app.use(pinia).mount('#login');